version: '3.6'

services:

  haproxy:
    build: ./haproxy
    ports:
      - 80:80

  backend:
    build: ./backend
    ports:
      - 8081:8080
    environment:
      - JWT_SECRET=test_environment_token

  frontend:
    build: ./frontend

  worker:
    build: ./vms-worker
    volumes:
      - /dev/vboxdrv:/dev/vboxdrv
      - ./vms-worker/dind:/var/lib/docker
      - ./vms-worker/labs:/labs
    network_mode: host
    privileged: true
    environment:
      - WORKER_ID=ourfirstone
      - MAIN_SERVER_URL=http://localhost:8081/api
      - WORKER_HOST=172.17.0.1
      - WORKER_PORT=8080
      - LABS_PATH=/labs
      - LAB_TEMPLATES_PATH=/app/vm