FROM python:3.6 as build

WORKDIR /build
COPY . .
RUN python setup.py sdist bdist_wheel

FROM python:3.6

WORKDIR /app
COPY --from=build /build/dist .
COPY ./setup_db.py ./setup_db.py

RUN pip install *.whl
RUN pip install waitress

RUN python setup_db.py

ENV FLASK_ENV="production"
ENTRYPOINT ["waitress-serve", "service_interface:app"]
